load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "io_bazel_rules_dotnet",
    sha256 = "6a1fa7a1b58e447c5b4520560cd44672f2379905b889580d6754f1de9b279bae",
    strip_prefix = "rules_dotnet-0.0.5",
    urls = ["https://github.com/bazelbuild/rules_dotnet/archive/0.0.5.zip"],
    ## WORKAROUND: Force nuget2bazel to get missing libraries from nuget
    #patches = [
    #   "//:rules_dotnet_nuget2bazel_buffers.patch",
    #],
    #patch_args = ["-p1"],
)

load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")

dotnet_repositories()

load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "core_register_sdk", "net_register_sdk", "mono_register_sdk",
    "dotnet_register_toolchains", "dotnet_repositories_nugets", "nuget_package")

dotnet_register_toolchains()
dotnet_repositories_nugets()

# For .NET Framework:
net_register_sdk(
    net_version = "net462",
    tools_version = "net462",
)

# (only useful for nuget2bazel)
core_register_sdk("v2.1.502", name = "core_sdk")


# bazel run @io_bazel_rules_dotnet//tools/nuget2bazel:nuget2bazel.exe -- add -l grpc 2.28.1 -p C:/path/to/rules_dotnet_memory_deps/
# bazel run @io_bazel_rules_dotnet//tools/nuget2bazel:nuget2bazel.exe -- add -l grpc.healthcheck 2.28.1 -p C:/path/to/rules_dotnet_memory_deps/

### Generated by the tool
nuget_package(
    name = "system.runtime.compilerservices.unsafe",
    package = "system.runtime.compilerservices.unsafe",
    version = "4.5.2",
    sha256 = "f1e5175c658ed8b2fbb804cc6727b6882a503844e7da309c8d4846e9ca11e4ef",
    core_lib = {
        "netcoreapp2.0": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netcoreapp2.1": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
    },
    net_lib = {
        "net45": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "net451": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "net452": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "net46": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "net461": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
        "net462": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
        "net47": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
        "net471": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
        "net472": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.0": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.1": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.2": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.3": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.4": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.5": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.6": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard2.0": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
    },
    mono_lib = "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
    core_files = {
        "netcoreapp2.0": [
           "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netcoreapp2.1": [
           "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
    },
    net_files = {
        "net45": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net451": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net452": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net46": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net461": [
           "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net462": [
           "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net47": [
           "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net471": [
           "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net472": [
           "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard1.0": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard1.1": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard1.2": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard1.3": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard1.4": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard1.5": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard1.6": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
    },
    mono_files = [
        "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
        "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.xml",
    ],
)
nuget_package(
    name = "system.memory",
    package = "system.memory",
    version = "4.5.3",
    sha256 = "0af97b45b45b46ef6a2b37910568dabd492c793da3859054595d523e2a545859",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/System.Memory.dll",
    },
    net_lib = {
        "net45": "lib/netstandard1.1/System.Memory.dll",
        "net451": "lib/netstandard1.1/System.Memory.dll",
        "net452": "lib/netstandard1.1/System.Memory.dll",
        "net46": "lib/netstandard1.1/System.Memory.dll",
        "net461": "lib/netstandard2.0/System.Memory.dll",
        "net462": "lib/netstandard2.0/System.Memory.dll",
        "net47": "lib/netstandard2.0/System.Memory.dll",
        "net471": "lib/netstandard2.0/System.Memory.dll",
        "net472": "lib/netstandard2.0/System.Memory.dll",
        "netstandard1.1": "lib/netstandard1.1/System.Memory.dll",
        "netstandard1.2": "lib/netstandard1.1/System.Memory.dll",
        "netstandard1.3": "lib/netstandard1.1/System.Memory.dll",
        "netstandard1.4": "lib/netstandard1.1/System.Memory.dll",
        "netstandard1.5": "lib/netstandard1.1/System.Memory.dll",
        "netstandard1.6": "lib/netstandard1.1/System.Memory.dll",
        "netstandard2.0": "lib/netstandard2.0/System.Memory.dll",
    },
    mono_lib = "lib/netstandard2.0/System.Memory.dll",
    core_deps = {
        "netcoreapp2.0": [
           "@system.runtime.compilerservices.unsafe//:netcoreapp2.0_core",
        ],
    },
    net_deps = {
        "net45": [
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net45_system.buffers.dll",
           "@system.runtime.compilerservices.unsafe//:net45_net",
        ],
        "net451": [
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net451_system.buffers.dll",
           "@system.runtime.compilerservices.unsafe//:net451_net",
        ],
        "net452": [
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net452_system.buffers.dll",
           "@system.runtime.compilerservices.unsafe//:net452_net",
        ],
        "net46": [
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net46_system.buffers.dll",
           "@system.runtime.compilerservices.unsafe//:net46_net",
        ],
        "net461": [
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net461_system.buffers.dll",
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net461_system.numerics.vectors.dll",
           "@system.runtime.compilerservices.unsafe//:net461_net",
        ],
        "net462": [
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net462_system.buffers.dll",
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net462_system.numerics.vectors.dll",
           "@system.runtime.compilerservices.unsafe//:net462_net",
        ],
        "net47": [
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net47_system.buffers.dll",
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net47_system.numerics.vectors.dll",
           "@system.runtime.compilerservices.unsafe//:net47_net",
        ],
        "net471": [
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net471_system.buffers.dll",
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net471_system.numerics.vectors.dll",
           "@system.runtime.compilerservices.unsafe//:net471_net",
        ],
        "net472": [
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net472_system.buffers.dll",
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net472_system.numerics.vectors.dll",
           "@system.runtime.compilerservices.unsafe//:net472_net",
        ],
        "netstandard1.1": [
           "@system.runtime.compilerservices.unsafe//:netstandard1.1_net",
        ],
        "netstandard1.2": [
           "@system.runtime.compilerservices.unsafe//:netstandard1.2_net",
        ],
        "netstandard1.3": [
           "@system.runtime.compilerservices.unsafe//:netstandard1.3_net",
        ],
        "netstandard1.4": [
           "@system.runtime.compilerservices.unsafe//:netstandard1.4_net",
        ],
        "netstandard1.5": [
           "@system.runtime.compilerservices.unsafe//:netstandard1.5_net",
        ],
        "netstandard1.6": [
           "@system.runtime.compilerservices.unsafe//:netstandard1.6_net",
        ],
        "netstandard2.0": [
           "@system.runtime.compilerservices.unsafe//:netstandard2.0_net",
        ],
    },
    mono_deps = [
        "@io_bazel_rules_dotnet//dotnet/stdlib:system.buffers.dll",
        "@io_bazel_rules_dotnet//dotnet/stdlib:system.numerics.vectors.dll",
        "@system.runtime.compilerservices.unsafe//:mono",
    ],
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard2.0/System.Memory.dll",
           "lib/netstandard2.0/System.Memory.xml",
        ],
    },
    net_files = {
        "net45": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "net451": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "net452": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "net46": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "net461": [
           "lib/netstandard2.0/System.Memory.dll",
           "lib/netstandard2.0/System.Memory.xml",
        ],
        "net462": [
           "lib/netstandard2.0/System.Memory.dll",
           "lib/netstandard2.0/System.Memory.xml",
        ],
        "net47": [
           "lib/netstandard2.0/System.Memory.dll",
           "lib/netstandard2.0/System.Memory.xml",
        ],
        "net471": [
           "lib/netstandard2.0/System.Memory.dll",
           "lib/netstandard2.0/System.Memory.xml",
        ],
        "net472": [
           "lib/netstandard2.0/System.Memory.dll",
           "lib/netstandard2.0/System.Memory.xml",
        ],
        "netstandard1.1": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "netstandard1.2": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "netstandard1.3": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "netstandard1.4": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "netstandard1.5": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "netstandard1.6": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/System.Memory.dll",
           "lib/netstandard2.0/System.Memory.xml",
        ],
    },
    mono_files = [
        "lib/netstandard2.0/System.Memory.dll",
        "lib/netstandard2.0/System.Memory.xml",
    ],
)
nuget_package(
    name = "grpc.core.api",
    package = "grpc.core.api",
    version = "2.28.1",
    sha256 = "f4abd6db983c1e8d99d53830aeb86b5ac6a9b2298295f496eec9451073d47760",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/Grpc.Core.Api.dll",
        "netcoreapp2.1": "lib/netstandard2.0/Grpc.Core.Api.dll",
    },
    net_lib = {
        "net45": "lib/net45/Grpc.Core.Api.dll",
        "net451": "lib/net45/Grpc.Core.Api.dll",
        "net452": "lib/net45/Grpc.Core.Api.dll",
        "net46": "lib/net45/Grpc.Core.Api.dll",
        "net461": "lib/net45/Grpc.Core.Api.dll",
        "net462": "lib/net45/Grpc.Core.Api.dll",
        "net47": "lib/net45/Grpc.Core.Api.dll",
        "net471": "lib/net45/Grpc.Core.Api.dll",
        "net472": "lib/net45/Grpc.Core.Api.dll",
        "netstandard1.5": "lib/netstandard1.5/Grpc.Core.Api.dll",
        "netstandard1.6": "lib/netstandard1.5/Grpc.Core.Api.dll",
        "netstandard2.0": "lib/netstandard2.0/Grpc.Core.Api.dll",
    },
    mono_lib = "lib/net45/Grpc.Core.Api.dll",
    core_deps = {
        "netcoreapp2.0": [
           "@system.memory//:netcoreapp2.0_core",
        ],
        "netcoreapp2.1": [
           "@system.memory//:netcoreapp2.1_core",
        ],
    },
    net_deps = {
        "net45": [
           "@system.memory//:net45_net",
        ],
        "net451": [
           "@system.memory//:net451_net",
        ],
        "net452": [
           "@system.memory//:net452_net",
        ],
        "net46": [
           "@system.memory//:net46_net",
        ],
        "net461": [
           "@system.memory//:net461_net",
        ],
        "net462": [
           "@system.memory//:net462_net",
        ],
        "net47": [
           "@system.memory//:net47_net",
        ],
        "net471": [
           "@system.memory//:net471_net",
        ],
        "net472": [
           "@system.memory//:net472_net",
        ],
        "netstandard1.5": [
           "@system.memory//:netstandard1.5_net",
        ],
        "netstandard1.6": [
           "@system.memory//:netstandard1.6_net",
        ],
        "netstandard2.0": [
           "@system.memory//:netstandard2.0_net",
        ],
    },
    mono_deps = [
        "@system.memory//:mono",
    ],
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard2.0/Grpc.Core.Api.dll",
           "lib/netstandard2.0/Grpc.Core.Api.pdb",
           "lib/netstandard2.0/Grpc.Core.Api.xml",
        ],
        "netcoreapp2.1": [
           "lib/netstandard2.0/Grpc.Core.Api.dll",
           "lib/netstandard2.0/Grpc.Core.Api.pdb",
           "lib/netstandard2.0/Grpc.Core.Api.xml",
        ],
    },
    net_files = {
        "net45": [
           "lib/net45/Grpc.Core.Api.dll",
           "lib/net45/Grpc.Core.Api.pdb",
           "lib/net45/Grpc.Core.Api.xml",
        ],
        "net451": [
           "lib/net45/Grpc.Core.Api.dll",
           "lib/net45/Grpc.Core.Api.pdb",
           "lib/net45/Grpc.Core.Api.xml",
        ],
        "net452": [
           "lib/net45/Grpc.Core.Api.dll",
           "lib/net45/Grpc.Core.Api.pdb",
           "lib/net45/Grpc.Core.Api.xml",
        ],
        "net46": [
           "lib/net45/Grpc.Core.Api.dll",
           "lib/net45/Grpc.Core.Api.pdb",
           "lib/net45/Grpc.Core.Api.xml",
        ],
        "net461": [
           "lib/net45/Grpc.Core.Api.dll",
           "lib/net45/Grpc.Core.Api.pdb",
           "lib/net45/Grpc.Core.Api.xml",
        ],
        "net462": [
           "lib/net45/Grpc.Core.Api.dll",
           "lib/net45/Grpc.Core.Api.pdb",
           "lib/net45/Grpc.Core.Api.xml",
        ],
        "net47": [
           "lib/net45/Grpc.Core.Api.dll",
           "lib/net45/Grpc.Core.Api.pdb",
           "lib/net45/Grpc.Core.Api.xml",
        ],
        "net471": [
           "lib/net45/Grpc.Core.Api.dll",
           "lib/net45/Grpc.Core.Api.pdb",
           "lib/net45/Grpc.Core.Api.xml",
        ],
        "net472": [
           "lib/net45/Grpc.Core.Api.dll",
           "lib/net45/Grpc.Core.Api.pdb",
           "lib/net45/Grpc.Core.Api.xml",
        ],
        "netstandard1.5": [
           "lib/netstandard1.5/Grpc.Core.Api.dll",
           "lib/netstandard1.5/Grpc.Core.Api.pdb",
           "lib/netstandard1.5/Grpc.Core.Api.xml",
        ],
        "netstandard1.6": [
           "lib/netstandard1.5/Grpc.Core.Api.dll",
           "lib/netstandard1.5/Grpc.Core.Api.pdb",
           "lib/netstandard1.5/Grpc.Core.Api.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/Grpc.Core.Api.dll",
           "lib/netstandard2.0/Grpc.Core.Api.pdb",
           "lib/netstandard2.0/Grpc.Core.Api.xml",
        ],
    },
    mono_files = [
        "lib/net45/Grpc.Core.Api.dll",
        "lib/net45/Grpc.Core.Api.pdb",
        "lib/net45/Grpc.Core.Api.xml",
    ],
)
nuget_package(
    name = "grpc.core",
    package = "grpc.core",
    version = "2.28.1",
    sha256 = "b625817b7e8dfe66e0894b232001b4c2f0e80aa41dc4dccb59d5a452ca36a755",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/Grpc.Core.dll",
        "netcoreapp2.1": "lib/netstandard2.0/Grpc.Core.dll",
    },
    net_lib = {
        "net45": "lib/net45/Grpc.Core.dll",
        "net451": "lib/net45/Grpc.Core.dll",
        "net452": "lib/net45/Grpc.Core.dll",
        "net46": "lib/net45/Grpc.Core.dll",
        "net461": "lib/net45/Grpc.Core.dll",
        "net462": "lib/net45/Grpc.Core.dll",
        "net47": "lib/net45/Grpc.Core.dll",
        "net471": "lib/net45/Grpc.Core.dll",
        "net472": "lib/net45/Grpc.Core.dll",
        "netstandard1.5": "lib/netstandard1.5/Grpc.Core.dll",
        "netstandard1.6": "lib/netstandard1.5/Grpc.Core.dll",
        "netstandard2.0": "lib/netstandard2.0/Grpc.Core.dll",
    },
    mono_lib = "lib/net45/Grpc.Core.dll",
    core_deps = {
        "netcoreapp2.0": [
           "@grpc.core.api//:netcoreapp2.0_core",
           "@system.memory//:netcoreapp2.0_core",
        ],
        "netcoreapp2.1": [
           "@grpc.core.api//:netcoreapp2.1_core",
           "@system.memory//:netcoreapp2.1_core",
        ],
    },
    net_deps = {
        "net45": [
           "@grpc.core.api//:net45_net",
           "@system.memory//:net45_net",
        ],
        "net451": [
           "@grpc.core.api//:net451_net",
           "@system.memory//:net451_net",
        ],
        "net452": [
           "@grpc.core.api//:net452_net",
           "@system.memory//:net452_net",
        ],
        "net46": [
           "@grpc.core.api//:net46_net",
           "@system.memory//:net46_net",
        ],
        "net461": [
           "@grpc.core.api//:net461_net",
           "@system.memory//:net461_net",
        ],
        "net462": [
           "@grpc.core.api//:net462_net",
           "@system.memory//:net462_net",
        ],
        "net47": [
           "@grpc.core.api//:net47_net",
           "@system.memory//:net47_net",
        ],
        "net471": [
           "@grpc.core.api//:net471_net",
           "@system.memory//:net471_net",
        ],
        "net472": [
           "@grpc.core.api//:net472_net",
           "@system.memory//:net472_net",
        ],
        "netstandard1.5": [
           "@grpc.core.api//:netstandard1.5_net",
           "@system.memory//:netstandard1.5_net",
        ],
        "netstandard1.6": [
           "@grpc.core.api//:netstandard1.6_net",
           "@system.memory//:netstandard1.6_net",
        ],
        "netstandard2.0": [
           "@grpc.core.api//:netstandard2.0_net",
           "@system.memory//:netstandard2.0_net",
        ],
    },
    mono_deps = [
        "@grpc.core.api//:mono",
        "@system.memory//:mono",
    ],
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard2.0/Grpc.Core.dll",
           "lib/netstandard2.0/Grpc.Core.pdb",
           "lib/netstandard2.0/Grpc.Core.xml",
        ],
        "netcoreapp2.1": [
           "lib/netstandard2.0/Grpc.Core.dll",
           "lib/netstandard2.0/Grpc.Core.pdb",
           "lib/netstandard2.0/Grpc.Core.xml",
        ],
    },
    net_files = {
        "net45": [
           "lib/net45/Grpc.Core.dll",
           "lib/net45/Grpc.Core.pdb",
           "lib/net45/Grpc.Core.xml",
        ],
        "net451": [
           "lib/net45/Grpc.Core.dll",
           "lib/net45/Grpc.Core.pdb",
           "lib/net45/Grpc.Core.xml",
        ],
        "net452": [
           "lib/net45/Grpc.Core.dll",
           "lib/net45/Grpc.Core.pdb",
           "lib/net45/Grpc.Core.xml",
        ],
        "net46": [
           "lib/net45/Grpc.Core.dll",
           "lib/net45/Grpc.Core.pdb",
           "lib/net45/Grpc.Core.xml",
        ],
        "net461": [
           "lib/net45/Grpc.Core.dll",
           "lib/net45/Grpc.Core.pdb",
           "lib/net45/Grpc.Core.xml",
        ],
        "net462": [
           "lib/net45/Grpc.Core.dll",
           "lib/net45/Grpc.Core.pdb",
           "lib/net45/Grpc.Core.xml",
        ],
        "net47": [
           "lib/net45/Grpc.Core.dll",
           "lib/net45/Grpc.Core.pdb",
           "lib/net45/Grpc.Core.xml",
        ],
        "net471": [
           "lib/net45/Grpc.Core.dll",
           "lib/net45/Grpc.Core.pdb",
           "lib/net45/Grpc.Core.xml",
        ],
        "net472": [
           "lib/net45/Grpc.Core.dll",
           "lib/net45/Grpc.Core.pdb",
           "lib/net45/Grpc.Core.xml",
        ],
        "netstandard1.5": [
           "lib/netstandard1.5/Grpc.Core.dll",
           "lib/netstandard1.5/Grpc.Core.pdb",
           "lib/netstandard1.5/Grpc.Core.xml",
        ],
        "netstandard1.6": [
           "lib/netstandard1.5/Grpc.Core.dll",
           "lib/netstandard1.5/Grpc.Core.pdb",
           "lib/netstandard1.5/Grpc.Core.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/Grpc.Core.dll",
           "lib/netstandard2.0/Grpc.Core.pdb",
           "lib/netstandard2.0/Grpc.Core.xml",
        ],
    },
    mono_files = [
        "lib/net45/Grpc.Core.dll",
        "lib/net45/Grpc.Core.pdb",
        "lib/net45/Grpc.Core.xml",
    ],
)
nuget_package(
    name = "grpc",
    package = "grpc",
    version = "2.28.1",
    sha256 = "e7f8b58ec80747ba8186c902a3be0e72f903745a44e177aab535a6b9876cfa9f",
    core_deps = {
        "netcoreapp2.0": [
           "@grpc.core//:netcoreapp2.0_core",
        ],
        "netcoreapp2.1": [
           "@grpc.core//:netcoreapp2.1_core",
        ],
    },
    net_deps = {
        "net45": [
           "@grpc.core//:net45_net",
        ],
        "net451": [
           "@grpc.core//:net451_net",
        ],
        "net452": [
           "@grpc.core//:net452_net",
        ],
        "net46": [
           "@grpc.core//:net46_net",
        ],
        "net461": [
           "@grpc.core//:net461_net",
        ],
        "net462": [
           "@grpc.core//:net462_net",
        ],
        "net47": [
           "@grpc.core//:net47_net",
        ],
        "net471": [
           "@grpc.core//:net471_net",
        ],
        "net472": [
           "@grpc.core//:net472_net",
        ],
        "netstandard1.5": [
           "@grpc.core//:netstandard1.5_net",
        ],
        "netstandard1.6": [
           "@grpc.core//:netstandard1.6_net",
        ],
        "netstandard2.0": [
           "@grpc.core//:netstandard2.0_net",
        ],
    },
    mono_deps = [
        "@grpc.core//:mono",
    ],
)
nuget_package(
    name = "google.protobuf",
    package = "google.protobuf",
    version = "3.11.2",
    sha256 = "f540fd572b7ca5b254764fc61483f236c71490936668a0c339038aa22356c34a",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/Google.Protobuf.dll",
        "netcoreapp2.1": "lib/netstandard2.0/Google.Protobuf.dll",
    },
    net_lib = {
        "net45": "lib/net45/Google.Protobuf.dll",
        "net451": "lib/net45/Google.Protobuf.dll",
        "net452": "lib/net45/Google.Protobuf.dll",
        "net46": "lib/net45/Google.Protobuf.dll",
        "net461": "lib/net45/Google.Protobuf.dll",
        "net462": "lib/net45/Google.Protobuf.dll",
        "net47": "lib/net45/Google.Protobuf.dll",
        "net471": "lib/net45/Google.Protobuf.dll",
        "net472": "lib/net45/Google.Protobuf.dll",
        "netstandard1.0": "lib/netstandard1.0/Google.Protobuf.dll",
        "netstandard1.1": "lib/netstandard1.0/Google.Protobuf.dll",
        "netstandard1.2": "lib/netstandard1.0/Google.Protobuf.dll",
        "netstandard1.3": "lib/netstandard1.0/Google.Protobuf.dll",
        "netstandard1.4": "lib/netstandard1.0/Google.Protobuf.dll",
        "netstandard1.5": "lib/netstandard1.0/Google.Protobuf.dll",
        "netstandard1.6": "lib/netstandard1.0/Google.Protobuf.dll",
        "netstandard2.0": "lib/netstandard2.0/Google.Protobuf.dll",
    },
    mono_lib = "lib/net45/Google.Protobuf.dll",
    core_deps = {
        "netcoreapp2.0": [
           "@system.memory//:netcoreapp2.0_core",
        ],
        "netcoreapp2.1": [
           "@system.memory//:netcoreapp2.1_core",
        ],
    },
    net_deps = {
        "net45": [
           "@system.memory//:net45_net",
        ],
        "net451": [
           "@system.memory//:net451_net",
        ],
        "net452": [
           "@system.memory//:net452_net",
        ],
        "net46": [
           "@system.memory//:net46_net",
        ],
        "net461": [
           "@system.memory//:net461_net",
        ],
        "net462": [
           "@system.memory//:net462_net",
        ],
        "net47": [
           "@system.memory//:net47_net",
        ],
        "net471": [
           "@system.memory//:net471_net",
        ],
        "net472": [
           "@system.memory//:net472_net",
        ],
        "netstandard2.0": [
           "@system.memory//:netstandard2.0_net",
        ],
    },
    mono_deps = [
        "@system.memory//:mono",
    ],
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard2.0/Google.Protobuf.dll",
           "lib/netstandard2.0/Google.Protobuf.pdb",
           "lib/netstandard2.0/Google.Protobuf.xml",
        ],
        "netcoreapp2.1": [
           "lib/netstandard2.0/Google.Protobuf.dll",
           "lib/netstandard2.0/Google.Protobuf.pdb",
           "lib/netstandard2.0/Google.Protobuf.xml",
        ],
    },
    net_files = {
        "net45": [
           "lib/net45/Google.Protobuf.dll",
           "lib/net45/Google.Protobuf.pdb",
           "lib/net45/Google.Protobuf.xml",
        ],
        "net451": [
           "lib/net45/Google.Protobuf.dll",
           "lib/net45/Google.Protobuf.pdb",
           "lib/net45/Google.Protobuf.xml",
        ],
        "net452": [
           "lib/net45/Google.Protobuf.dll",
           "lib/net45/Google.Protobuf.pdb",
           "lib/net45/Google.Protobuf.xml",
        ],
        "net46": [
           "lib/net45/Google.Protobuf.dll",
           "lib/net45/Google.Protobuf.pdb",
           "lib/net45/Google.Protobuf.xml",
        ],
        "net461": [
           "lib/net45/Google.Protobuf.dll",
           "lib/net45/Google.Protobuf.pdb",
           "lib/net45/Google.Protobuf.xml",
        ],
        "net462": [
           "lib/net45/Google.Protobuf.dll",
           "lib/net45/Google.Protobuf.pdb",
           "lib/net45/Google.Protobuf.xml",
        ],
        "net47": [
           "lib/net45/Google.Protobuf.dll",
           "lib/net45/Google.Protobuf.pdb",
           "lib/net45/Google.Protobuf.xml",
        ],
        "net471": [
           "lib/net45/Google.Protobuf.dll",
           "lib/net45/Google.Protobuf.pdb",
           "lib/net45/Google.Protobuf.xml",
        ],
        "net472": [
           "lib/net45/Google.Protobuf.dll",
           "lib/net45/Google.Protobuf.pdb",
           "lib/net45/Google.Protobuf.xml",
        ],
        "netstandard1.0": [
           "lib/netstandard1.0/Google.Protobuf.dll",
           "lib/netstandard1.0/Google.Protobuf.pdb",
           "lib/netstandard1.0/Google.Protobuf.xml",
        ],
        "netstandard1.1": [
           "lib/netstandard1.0/Google.Protobuf.dll",
           "lib/netstandard1.0/Google.Protobuf.pdb",
           "lib/netstandard1.0/Google.Protobuf.xml",
        ],
        "netstandard1.2": [
           "lib/netstandard1.0/Google.Protobuf.dll",
           "lib/netstandard1.0/Google.Protobuf.pdb",
           "lib/netstandard1.0/Google.Protobuf.xml",
        ],
        "netstandard1.3": [
           "lib/netstandard1.0/Google.Protobuf.dll",
           "lib/netstandard1.0/Google.Protobuf.pdb",
           "lib/netstandard1.0/Google.Protobuf.xml",
        ],
        "netstandard1.4": [
           "lib/netstandard1.0/Google.Protobuf.dll",
           "lib/netstandard1.0/Google.Protobuf.pdb",
           "lib/netstandard1.0/Google.Protobuf.xml",
        ],
        "netstandard1.5": [
           "lib/netstandard1.0/Google.Protobuf.dll",
           "lib/netstandard1.0/Google.Protobuf.pdb",
           "lib/netstandard1.0/Google.Protobuf.xml",
        ],
        "netstandard1.6": [
           "lib/netstandard1.0/Google.Protobuf.dll",
           "lib/netstandard1.0/Google.Protobuf.pdb",
           "lib/netstandard1.0/Google.Protobuf.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/Google.Protobuf.dll",
           "lib/netstandard2.0/Google.Protobuf.pdb",
           "lib/netstandard2.0/Google.Protobuf.xml",
        ],
    },
    mono_files = [
        "lib/net45/Google.Protobuf.dll",
        "lib/net45/Google.Protobuf.pdb",
        "lib/net45/Google.Protobuf.xml",
    ],
)
nuget_package(
    name = "system.threading.channels",
    package = "system.threading.channels",
    version = "4.6.0",
    sha256 = "42d6eb4a5023bb237e5d19e715d67ce99e1e0ccea186e247bb5aa222eacb795a",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/System.Threading.Channels.dll",
        "netcoreapp2.1": "lib/netstandard2.0/System.Threading.Channels.dll",
    },
    net_lib = {
        "net46": "lib/netstandard1.3/System.Threading.Channels.dll",
        "net461": "lib/netstandard2.0/System.Threading.Channels.dll",
        "net462": "lib/netstandard2.0/System.Threading.Channels.dll",
        "net47": "lib/netstandard2.0/System.Threading.Channels.dll",
        "net471": "lib/netstandard2.0/System.Threading.Channels.dll",
        "net472": "lib/netstandard2.0/System.Threading.Channels.dll",
        "netstandard1.3": "lib/netstandard1.3/System.Threading.Channels.dll",
        "netstandard1.4": "lib/netstandard1.3/System.Threading.Channels.dll",
        "netstandard1.5": "lib/netstandard1.3/System.Threading.Channels.dll",
        "netstandard1.6": "lib/netstandard1.3/System.Threading.Channels.dll",
        "netstandard2.0": "lib/netstandard2.0/System.Threading.Channels.dll",
    },
    mono_lib = "lib/netstandard2.0/System.Threading.Channels.dll",
    net_deps = {
        "net46": [
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net46_system.threading.tasks.extensions.dll",
        ],
        "net461": [
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net461_system.threading.tasks.extensions.dll",
        ],
        "net462": [
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net462_system.threading.tasks.extensions.dll",
        ],
        "net47": [
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net47_system.threading.tasks.extensions.dll",
        ],
        "net471": [
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net471_system.threading.tasks.extensions.dll",
        ],
        "net472": [
           "@io_bazel_rules_dotnet//dotnet/stdlib.net:net472_system.threading.tasks.extensions.dll",
        ],
    },
    mono_deps = [
        "@io_bazel_rules_dotnet//dotnet/stdlib:system.threading.tasks.extensions.dll",
    ],
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard2.0/System.Threading.Channels.dll",
           "lib/netstandard2.0/System.Threading.Channels.xml",
        ],
        "netcoreapp2.1": [
           "lib/netstandard2.0/System.Threading.Channels.dll",
           "lib/netstandard2.0/System.Threading.Channels.xml",
        ],
    },
    net_files = {
        "net46": [
           "lib/netstandard1.3/System.Threading.Channels.dll",
           "lib/netstandard1.3/System.Threading.Channels.xml",
        ],
        "net461": [
           "lib/netstandard2.0/System.Threading.Channels.dll",
           "lib/netstandard2.0/System.Threading.Channels.xml",
        ],
        "net462": [
           "lib/netstandard2.0/System.Threading.Channels.dll",
           "lib/netstandard2.0/System.Threading.Channels.xml",
        ],
        "net47": [
           "lib/netstandard2.0/System.Threading.Channels.dll",
           "lib/netstandard2.0/System.Threading.Channels.xml",
        ],
        "net471": [
           "lib/netstandard2.0/System.Threading.Channels.dll",
           "lib/netstandard2.0/System.Threading.Channels.xml",
        ],
        "net472": [
           "lib/netstandard2.0/System.Threading.Channels.dll",
           "lib/netstandard2.0/System.Threading.Channels.xml",
        ],
        "netstandard1.3": [
           "lib/netstandard1.3/System.Threading.Channels.dll",
           "lib/netstandard1.3/System.Threading.Channels.xml",
        ],
        "netstandard1.4": [
           "lib/netstandard1.3/System.Threading.Channels.dll",
           "lib/netstandard1.3/System.Threading.Channels.xml",
        ],
        "netstandard1.5": [
           "lib/netstandard1.3/System.Threading.Channels.dll",
           "lib/netstandard1.3/System.Threading.Channels.xml",
        ],
        "netstandard1.6": [
           "lib/netstandard1.3/System.Threading.Channels.dll",
           "lib/netstandard1.3/System.Threading.Channels.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/System.Threading.Channels.dll",
           "lib/netstandard2.0/System.Threading.Channels.xml",
        ],
    },
    mono_files = [
        "lib/netstandard2.0/System.Threading.Channels.dll",
        "lib/netstandard2.0/System.Threading.Channels.xml",
    ],
)
nuget_package(
    name = "grpc.healthcheck",
    package = "grpc.healthcheck",
    version = "2.28.1",
    sha256 = "7e1761d5e0f2339e6805cfd7d345bff53f4ae61a7a951a19d5ed9b065fa91065",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/Grpc.HealthCheck.dll",
        "netcoreapp2.1": "lib/netstandard2.0/Grpc.HealthCheck.dll",
    },
    net_lib = {
        "net45": "lib/net45/Grpc.HealthCheck.dll",
        "net451": "lib/net45/Grpc.HealthCheck.dll",
        "net452": "lib/net45/Grpc.HealthCheck.dll",
        "net46": "lib/net45/Grpc.HealthCheck.dll",
        "net461": "lib/net45/Grpc.HealthCheck.dll",
        "net462": "lib/net462/Grpc.HealthCheck.dll",
        "net47": "lib/net462/Grpc.HealthCheck.dll",
        "net471": "lib/net462/Grpc.HealthCheck.dll",
        "net472": "lib/net462/Grpc.HealthCheck.dll",
        "netstandard1.5": "lib/netstandard1.5/Grpc.HealthCheck.dll",
        "netstandard1.6": "lib/netstandard1.5/Grpc.HealthCheck.dll",
        "netstandard2.0": "lib/netstandard2.0/Grpc.HealthCheck.dll",
    },
    mono_lib = "lib/net462/Grpc.HealthCheck.dll",
    core_deps = {
        "netcoreapp2.0": [
           "@grpc.core.api//:netcoreapp2.0_core",
           "@google.protobuf//:netcoreapp2.0_core",
           "@system.threading.channels//:netcoreapp2.0_core",
        ],
        "netcoreapp2.1": [
           "@grpc.core.api//:netcoreapp2.1_core",
           "@google.protobuf//:netcoreapp2.1_core",
           "@system.threading.channels//:netcoreapp2.1_core",
        ],
    },
    net_deps = {
        "net45": [
           "@grpc.core.api//:net45_net",
           "@google.protobuf//:net45_net",
        ],
        "net451": [
           "@grpc.core.api//:net451_net",
           "@google.protobuf//:net451_net",
        ],
        "net452": [
           "@grpc.core.api//:net452_net",
           "@google.protobuf//:net452_net",
        ],
        "net46": [
           "@grpc.core.api//:net46_net",
           "@google.protobuf//:net46_net",
        ],
        "net461": [
           "@grpc.core.api//:net461_net",
           "@google.protobuf//:net461_net",
        ],
        "net462": [
           "@grpc.core.api//:net462_net",
           "@google.protobuf//:net462_net",
           "@system.threading.channels//:net462_net",
        ],
        "net47": [
           "@grpc.core.api//:net47_net",
           "@google.protobuf//:net47_net",
           "@system.threading.channels//:net47_net",
        ],
        "net471": [
           "@grpc.core.api//:net471_net",
           "@google.protobuf//:net471_net",
           "@system.threading.channels//:net471_net",
        ],
        "net472": [
           "@grpc.core.api//:net472_net",
           "@google.protobuf//:net472_net",
           "@system.threading.channels//:net472_net",
        ],
        "netstandard1.5": [
           "@grpc.core.api//:netstandard1.5_net",
           "@google.protobuf//:netstandard1.5_net",
           "@system.threading.channels//:netstandard1.5_net",
        ],
        "netstandard1.6": [
           "@grpc.core.api//:netstandard1.6_net",
           "@google.protobuf//:netstandard1.6_net",
           "@system.threading.channels//:netstandard1.6_net",
        ],
        "netstandard2.0": [
           "@grpc.core.api//:netstandard2.0_net",
           "@google.protobuf//:netstandard2.0_net",
           "@system.threading.channels//:netstandard2.0_net",
        ],
    },
    mono_deps = [
        "@grpc.core.api//:mono",
        "@google.protobuf//:mono",
        "@system.threading.channels//:mono",
    ],
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard2.0/Grpc.HealthCheck.dll",
           "lib/netstandard2.0/Grpc.HealthCheck.pdb",
           "lib/netstandard2.0/Grpc.HealthCheck.xml",
        ],
        "netcoreapp2.1": [
           "lib/netstandard2.0/Grpc.HealthCheck.dll",
           "lib/netstandard2.0/Grpc.HealthCheck.pdb",
           "lib/netstandard2.0/Grpc.HealthCheck.xml",
        ],
    },
    net_files = {
        "net45": [
           "lib/net45/Grpc.HealthCheck.dll",
           "lib/net45/Grpc.HealthCheck.pdb",
           "lib/net45/Grpc.HealthCheck.xml",
        ],
        "net451": [
           "lib/net45/Grpc.HealthCheck.dll",
           "lib/net45/Grpc.HealthCheck.pdb",
           "lib/net45/Grpc.HealthCheck.xml",
        ],
        "net452": [
           "lib/net45/Grpc.HealthCheck.dll",
           "lib/net45/Grpc.HealthCheck.pdb",
           "lib/net45/Grpc.HealthCheck.xml",
        ],
        "net46": [
           "lib/net45/Grpc.HealthCheck.dll",
           "lib/net45/Grpc.HealthCheck.pdb",
           "lib/net45/Grpc.HealthCheck.xml",
        ],
        "net461": [
           "lib/net45/Grpc.HealthCheck.dll",
           "lib/net45/Grpc.HealthCheck.pdb",
           "lib/net45/Grpc.HealthCheck.xml",
        ],
        "net462": [
           "lib/net462/Grpc.HealthCheck.dll",
           "lib/net462/Grpc.HealthCheck.pdb",
           "lib/net462/Grpc.HealthCheck.xml",
        ],
        "net47": [
           "lib/net462/Grpc.HealthCheck.dll",
           "lib/net462/Grpc.HealthCheck.pdb",
           "lib/net462/Grpc.HealthCheck.xml",
        ],
        "net471": [
           "lib/net462/Grpc.HealthCheck.dll",
           "lib/net462/Grpc.HealthCheck.pdb",
           "lib/net462/Grpc.HealthCheck.xml",
        ],
        "net472": [
           "lib/net462/Grpc.HealthCheck.dll",
           "lib/net462/Grpc.HealthCheck.pdb",
           "lib/net462/Grpc.HealthCheck.xml",
        ],
        "netstandard1.5": [
           "lib/netstandard1.5/Grpc.HealthCheck.dll",
           "lib/netstandard1.5/Grpc.HealthCheck.pdb",
           "lib/netstandard1.5/Grpc.HealthCheck.xml",
        ],
        "netstandard1.6": [
           "lib/netstandard1.5/Grpc.HealthCheck.dll",
           "lib/netstandard1.5/Grpc.HealthCheck.pdb",
           "lib/netstandard1.5/Grpc.HealthCheck.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/Grpc.HealthCheck.dll",
           "lib/netstandard2.0/Grpc.HealthCheck.pdb",
           "lib/netstandard2.0/Grpc.HealthCheck.xml",
        ],
    },
    mono_files = [
        "lib/net462/Grpc.HealthCheck.dll",
        "lib/net462/Grpc.HealthCheck.pdb",
        "lib/net462/Grpc.HealthCheck.xml",
    ],
)
### End of generated by the tool
